# Generated by Django 6.0.6 on 2026-08-09 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0007_alter_category_options_rename_category_tag_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag']},
        ),
    ]
